// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RUSAL.MetalTapping.DAL.Contexts;

#nullable disable

namespace RUSAL.MetalTapping.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260120084832_UpdateStructure")]
    partial class UpdateStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ChemicalElem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ChemicalElems");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Deviation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotReglamentId")
                        .HasColumnType("int");

                    b.Property<double>("TargetMetalLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PotReglamentId");

                    b.ToTable("Deviations");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationValues", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("CastingRatio")
                        .HasColumnType("float");

                    b.Property<int>("DeviationId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DeviationId");

                    b.ToTable("DeviationValues");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ExternalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfReceipt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PotId")
                        .HasColumnType("int");

                    b.Property<int>("PotParametersGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.HasIndex("PotParametersGroupId");

                    b.ToTable("ExternalDatas");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetalMarks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MetalMarkAnalyses");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChemicalElemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfReceipt")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetalMarkAnalysisId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalElemId");

                    b.HasIndex("MetalMarkAnalysisId");

                    b.ToTable("MetalMarkAnalysisValues");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfOrder")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetalMarkId")
                        .HasColumnType("int");

                    b.Property<double>("WeightOfMetal")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("MetalMarkId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Pot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("StateId");

                    b.ToTable("Pots");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PotParametersGroupId")
                        .HasColumnType("int");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("PotParametersGroupId");

                    b.ToTable("PotParameters");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParametersGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("PotParametersGroups");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotReglament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("PotId")
                        .HasColumnType("int");

                    b.Property<int>("ReglamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.HasIndex("ReglamentId");

                    b.ToTable("PotReglaments");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PotStates");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Reglament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStop")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Reglaments");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Scoop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScoopStateId")
                        .HasColumnType("int");

                    b.Property<int>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ScoopStateId");

                    b.ToTable("Scoops");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ScoopStates");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Shift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("WorkGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("Shifts");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ShiftTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ShiftId")
                        .HasColumnType("int");

                    b.Property<int>("TapTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ScoopId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ScoopId");

                    b.ToTable("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskPot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MetalMarkAnalysisId")
                        .HasColumnType("int");

                    b.Property<int>("PotId")
                        .HasColumnType("int");

                    b.Property<double>("PotMetalWeigth")
                        .HasColumnType("float");

                    b.Property<int>("TapTaskId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MetalMarkAnalysisId");

                    b.HasIndex("PotId");

                    b.HasIndex("TapTaskId");

                    b.ToTable("TapTaskPots");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.UserRoleMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleMembers");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkGroups");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroupMembers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("WorkGroupMembers");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Deviation", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotReglament", "PotReglament")
                        .WithMany("Deviations")
                        .HasForeignKey("PotReglamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PotReglament");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationValues", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Deviation", "Deviation")
                        .WithMany("DeviationValues")
                        .HasForeignKey("DeviationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deviation");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ExternalData", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Pot", "Pot")
                        .WithMany()
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotParametersGroup", "Parameters")
                        .WithMany()
                        .HasForeignKey("PotParametersGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameters");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisValue", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ChemicalElem", "ChemicalElem")
                        .WithMany()
                        .HasForeignKey("ChemicalElemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysis", "Analysis")
                        .WithMany("Values")
                        .HasForeignKey("MetalMarkAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("ChemicalElem");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Order", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMark", "MetalMark")
                        .WithMany("Orders")
                        .HasForeignKey("MetalMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetalMark");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Pot", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Building", "Building")
                        .WithMany("Pots")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotState", "State")
                        .WithMany()
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("State");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParameter", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotParametersGroup", "Group")
                        .WithMany("Parameters")
                        .HasForeignKey("PotParametersGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotReglament", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Pot", "Pot")
                        .WithMany()
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Reglament", "Reglament")
                        .WithMany()
                        .HasForeignKey("ReglamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");

                    b.Navigation("Reglament");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Scoop", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Building", "Building")
                        .WithMany("Scoops")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ScoopState", "ScoopState")
                        .WithMany()
                        .HasForeignKey("ScoopStateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("ScoopState");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Shift", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.WorkGroup", "WorkGroup")
                        .WithMany("Shifts")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTask", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Building", "Building")
                        .WithMany("TapTasks")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Order", "Order")
                        .WithMany("TapTasks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Scoop", "Scoop")
                        .WithMany("TapTasks")
                        .HasForeignKey("ScoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Order");

                    b.Navigation("Scoop");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskPot", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysis", "Analysis")
                        .WithMany("TapTaskPots")
                        .HasForeignKey("MetalMarkAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Pot", "Pot")
                        .WithMany()
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.TapTask", "TapTask")
                        .WithMany()
                        .HasForeignKey("TapTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Pot");

                    b.Navigation("TapTask");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.User", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.WorkGroup", null)
                        .WithMany("Users")
                        .HasForeignKey("WorkGroupId");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.UserRoleMembers", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.Role", "Role")
                        .WithMany("UserRoleMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.User", "User")
                        .WithMany("UserRoleMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroupMembers", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.User", "User")
                        .WithMany("WorkGroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.WorkGroup", "WorkGroup")
                        .WithMany("WorkGroupMembers")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Building", b =>
                {
                    b.Navigation("Pots");

                    b.Navigation("Scoops");

                    b.Navigation("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Deviation", b =>
                {
                    b.Navigation("DeviationValues");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMark", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysis", b =>
                {
                    b.Navigation("TapTaskPots");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Order", b =>
                {
                    b.Navigation("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParametersGroup", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotReglament", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Role", b =>
                {
                    b.Navigation("UserRoleMembers");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.Scoop", b =>
                {
                    b.Navigation("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.User", b =>
                {
                    b.Navigation("UserRoleMembers");

                    b.Navigation("WorkGroupMembers");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroup", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("Users");

                    b.Navigation("WorkGroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
