// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RUSAL.MetalTapping.DAL.Contexts;

#nullable disable

namespace RUSAL.MetalTapping.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260413102735_AddTasksRelations")]
    partial class AddTasksRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.BuildingModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Building", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.CalculatedTaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal?>("CalculatedTaskForPot")
                        .HasColumnType("numeric(18, 4)")
                        .HasColumnName("CalculatedTask");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PotId");

                    b.Property<decimal?>("RoundCalculatedTaskForPot")
                        .HasColumnType("numeric(18, 4)")
                        .HasColumnName("RoundCalculatedTask");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.ToTable("CalculatedTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ChemicalElemModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ChemicalElem", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<decimal?>("ActualMetalLevel")
                        .HasColumnType("numeric(4, 0)")
                        .HasColumnName("ActualMetalLevel");

                    b.Property<bool?>("IsValid")
                        .HasColumnType("bit")
                        .HasColumnName("IsValid");

                    b.Property<Guid>("PotReglamentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TargetMetalLevel")
                        .HasColumnType("numeric(4, 0)")
                        .HasColumnName("TargetMetalLevel");

                    b.HasKey("Id");

                    b.HasIndex("PotReglamentId");

                    b.ToTable("Deviation", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationValuesModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CastingRatio")
                        .HasColumnType("int")
                        .HasColumnName("CastingRatio");

                    b.Property<Guid>("DeviationId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeviationID");

                    b.Property<int>("Value")
                        .HasColumnType("int")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("DeviationId");

                    b.ToTable("DeviationValues", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ExternalDataModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfReceipt")
                        .HasColumnType("date")
                        .HasColumnName("DateOfReceipt");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotParametersGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.HasIndex("PotParametersGroupId");

                    b.ToTable("ExternalData", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfReceipt")
                        .HasColumnType("date")
                        .HasColumnName("DateOfReceipt");

                    b.Property<Guid>("MetalMarkId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MetalMarkId");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PotId");

                    b.HasKey("Id");

                    b.HasIndex("MetalMarkId");

                    b.HasIndex("PotId");

                    b.ToTable("MetalMarkAnalysis", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisValueModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("ChemicalElemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MetalMarkAnalysisId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("MetalMarkAnalysisID");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("ChemicalElemId");

                    b.HasIndex("MetalMarkAnalysisId");

                    b.ToTable("MetalMarkAnalysisValues", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("MetalMark", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.OrderModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DateOfOrder")
                        .HasColumnType("datetime")
                        .HasColumnName("DateOfOrder");

                    b.Property<Guid>("MetalMarkId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("WeightOfMetal")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("WeightOfMetal");

                    b.HasKey("Id");

                    b.HasIndex("MetalMarkId");

                    b.ToTable("Order", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotGroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("BuildingId");

                    b.Property<Guid>("ScoopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ScoopId");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("ScoopId");

                    b.ToTable("PotGroup", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotGroupsHistoryModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime")
                        .HasColumnName("Date");

                    b.Property<Guid>("PotGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PotGroupId");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("PotId");

                    b.HasKey("Id");

                    b.HasIndex("PotGroupId");

                    b.HasIndex("PotId");

                    b.ToTable("PotGroupsHistory", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Name");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("StateId");

                    b.ToTable("Pot", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParameterModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<Guid>("PotParametersGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.HasIndex("PotParametersGroupId");

                    b.ToTable("PotParameters", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParametersGroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.HasKey("Id");

                    b.ToTable("PotParametersGroup", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotReglamentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReglamentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PotId");

                    b.HasIndex("ReglamentId");

                    b.ToTable("PotReglament", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotStateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("PotState", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ReglamentModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("DateStart")
                        .HasColumnType("datetime")
                        .HasColumnName("DateStart");

                    b.Property<DateTime>("DateStop")
                        .HasColumnType("datetime")
                        .HasColumnName("DateStop");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Reglament", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.RoleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<Guid>("StateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Scoop", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopStateModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("ScoopState", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopUsageModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime?>("BusyFrom")
                        .HasColumnType("datetime")
                        .HasColumnName("BusyFrom");

                    b.Property<DateTime?>("BusyUntil")
                        .HasColumnType("datetime")
                        .HasColumnName("BusyUntil");

                    b.Property<Guid>("ScoopId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ScoopId");

                    b.HasKey("Id");

                    b.HasIndex("ScoopId");

                    b.ToTable("ScoopUsage", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ShiftModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("BeginDate")
                        .HasColumnType("datetime")
                        .HasColumnName("BeginDate");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime")
                        .HasColumnName("EndDate");

                    b.Property<Guid>("WorkGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("Shift", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ScoopId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("OrderId");

                    b.HasIndex("ScoopId");

                    b.ToTable("TapTasks", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskPotModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("MetalMarkAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PotId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("PotMetalWeigth")
                        .HasColumnType("numeric(10, 0)")
                        .HasColumnName("PotMetalWeight");

                    b.Property<Guid>("TapTaskId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MetalMarkAnalysisId");

                    b.HasIndex("PotId");

                    b.HasIndex("TapTaskId");

                    b.ToTable("TapTaskPot", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TaskModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<byte[]>("LeadTime")
                        .IsRequired()
                        .HasColumnType("timestamp")
                        .HasColumnName("LeadTime");

                    b.Property<Guid>("ShiftId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ShiftId");

                    b.Property<Guid>("TapTaskId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("TapTaskId");

                    b.HasKey("Id");

                    b.HasIndex("ShiftId");

                    b.HasIndex("TapTaskId");

                    b.ToTable("Tasks", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.UserModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("FirstName");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LastName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("Password");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.UserRoleMembersModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("RoleId");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoleMembers", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroupMembersModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("UserId");

                    b.Property<Guid>("WorkGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("WorkGroupId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkGroupId");

                    b.ToTable("WorkGroupMembers", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroupModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.HasKey("Id");

                    b.ToTable("WorkGroup", (string)null);
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.CalculatedTaskModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotModel", "Pot")
                        .WithMany("calculatedTasks")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotReglamentModel", "PotReglament")
                        .WithMany("Deviations")
                        .HasForeignKey("PotReglamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PotReglament");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationValuesModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.DeviationModel", "Deviation")
                        .WithMany("DeviationValues")
                        .HasForeignKey("DeviationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deviation");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ExternalDataModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotModel", "Pot")
                        .WithMany("ExternalDatas")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotParametersGroupModel", "Parameters")
                        .WithMany()
                        .HasForeignKey("PotParametersGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Parameters");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMarkModel", "MetalMark")
                        .WithMany("Analyses")
                        .HasForeignKey("MetalMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotModel", "Pot")
                        .WithMany("metalMarkAnalyses")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetalMark");

                    b.Navigation("Pot");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisValueModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ChemicalElemModel", "ChemicalElem")
                        .WithMany("Values")
                        .HasForeignKey("ChemicalElemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisModel", "Analysis")
                        .WithMany("Values")
                        .HasForeignKey("MetalMarkAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("ChemicalElem");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.OrderModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMarkModel", "MetalMark")
                        .WithMany("Orders")
                        .HasForeignKey("MetalMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MetalMark");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotGroupModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.BuildingModel", "Building")
                        .WithMany("PotGroupModels")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ScoopModel", "Scoop")
                        .WithMany()
                        .HasForeignKey("ScoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Scoop");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotGroupsHistoryModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotGroupModel", "PotGroup")
                        .WithMany("History")
                        .HasForeignKey("PotGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotModel", "Pot")
                        .WithMany("GroupsHistory")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");

                    b.Navigation("PotGroup");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.BuildingModel", "Building")
                        .WithMany("Pots")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotStateModel", "State")
                        .WithMany("Pots")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("State");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParameterModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotParametersGroupModel", "Group")
                        .WithMany("Parameters")
                        .HasForeignKey("PotParametersGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotReglamentModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotModel", "Pot")
                        .WithMany("Reglaments")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ReglamentModel", "Reglament")
                        .WithMany("Reglaments")
                        .HasForeignKey("ReglamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pot");

                    b.Navigation("Reglament");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ScoopStateModel", "ScoopState")
                        .WithMany("Scoops")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScoopState");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopUsageModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ScoopModel", "Scoop")
                        .WithMany("ScoopUsageModels")
                        .HasForeignKey("ScoopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scoop");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ShiftModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.WorkGroupModel", "WorkGroup")
                        .WithMany("Shifts")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.BuildingModel", "Building")
                        .WithMany("TapTasks")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.OrderModel", "Order")
                        .WithMany("TapTasks")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ScoopModel", "Scoop")
                        .WithMany("TapTasks")
                        .HasForeignKey("ScoopId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Order");

                    b.Navigation("Scoop");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskPotModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisModel", "Analysis")
                        .WithMany("TapTaskPots")
                        .HasForeignKey("MetalMarkAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.PotModel", "Pot")
                        .WithMany("TapTaskPots")
                        .HasForeignKey("PotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.TapTaskModel", "TapTask")
                        .WithMany("TapTaskPots")
                        .HasForeignKey("TapTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Analysis");

                    b.Navigation("Pot");

                    b.Navigation("TapTask");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TaskModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.ShiftModel", "Shift")
                        .WithMany("Tasks")
                        .HasForeignKey("ShiftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.TapTaskModel", "TapTask")
                        .WithMany("Tasks")
                        .HasForeignKey("TapTaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shift");

                    b.Navigation("TapTask");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.UserRoleMembersModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.RoleModel", "Role")
                        .WithMany("UserRoleMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.UserModel", "User")
                        .WithMany("UserRoleMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroupMembersModel", b =>
                {
                    b.HasOne("RUSAL.MetalTapping.DAL.Models.UserModel", "User")
                        .WithMany("WorkGroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RUSAL.MetalTapping.DAL.Models.WorkGroupModel", "WorkGroup")
                        .WithMany("WorkGroupMembers")
                        .HasForeignKey("WorkGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");

                    b.Navigation("WorkGroup");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.BuildingModel", b =>
                {
                    b.Navigation("PotGroupModels");

                    b.Navigation("Pots");

                    b.Navigation("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ChemicalElemModel", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.DeviationModel", b =>
                {
                    b.Navigation("DeviationValues");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkAnalysisModel", b =>
                {
                    b.Navigation("TapTaskPots");

                    b.Navigation("Values");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.MetalMarkModel", b =>
                {
                    b.Navigation("Analyses");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.OrderModel", b =>
                {
                    b.Navigation("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotGroupModel", b =>
                {
                    b.Navigation("History");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotModel", b =>
                {
                    b.Navigation("ExternalDatas");

                    b.Navigation("GroupsHistory");

                    b.Navigation("Reglaments");

                    b.Navigation("TapTaskPots");

                    b.Navigation("calculatedTasks");

                    b.Navigation("metalMarkAnalyses");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotParametersGroupModel", b =>
                {
                    b.Navigation("Parameters");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotReglamentModel", b =>
                {
                    b.Navigation("Deviations");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.PotStateModel", b =>
                {
                    b.Navigation("Pots");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ReglamentModel", b =>
                {
                    b.Navigation("Reglaments");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.RoleModel", b =>
                {
                    b.Navigation("UserRoleMembers");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopModel", b =>
                {
                    b.Navigation("ScoopUsageModels");

                    b.Navigation("TapTasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ScoopStateModel", b =>
                {
                    b.Navigation("Scoops");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.ShiftModel", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.TapTaskModel", b =>
                {
                    b.Navigation("TapTaskPots");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.UserModel", b =>
                {
                    b.Navigation("UserRoleMembers");

                    b.Navigation("WorkGroupMembers");
                });

            modelBuilder.Entity("RUSAL.MetalTapping.DAL.Models.WorkGroupModel", b =>
                {
                    b.Navigation("Shifts");

                    b.Navigation("WorkGroupMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
